<?php if (!defined('ABSPATH')) exit; ?>
<div class="wrap wpbb-analytics-wrap">
    <div class="wpbb-analytics-head">
        <div><span class="wpbb-analytics-kicker">WP BB PLATFORM</span><h1><?php esc_html_e('Website statistics', 'wp-bbuilder'); ?></h1><p><?php esc_html_e('First-party traffic intelligence for pages, products, countries, devices and acquisition sources.', 'wp-bbuilder'); ?></p></div>
        <div class="wpbb-analytics-actions"><a class="button" href="<?php echo esc_url($settings_url); ?>"><?php esc_html_e('Analytics settings', 'wp-bbuilder'); ?></a><a class="button" href="<?php echo esc_url($full_settings_url); ?>"><?php esc_html_e('BBuilder settings', 'wp-bbuilder'); ?></a></div>
    </div>
    <form class="wpbb-range" method="get"><input type="hidden" name="page" value="wpbb-analytics"><label for="wpbb-range"><?php esc_html_e('Range', 'wp-bbuilder'); ?></label><select id="wpbb-range" name="range" onchange="this.form.submit()"><?php foreach ([7,30,90,180,365] as $d): ?><option value="<?php echo esc_attr($d); ?>" <?php selected($days,$d); ?>><?php echo esc_html(sprintf(_n('%d day','%d days',$d,'wp-bbuilder'),$d)); ?></option><?php endforeach; ?></select></form>

    <div class="wpbb-kpis">
        <div class="wpbb-kpi"><span><?php esc_html_e('Page views','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($views)); ?></strong><em class="<?php echo $view_growth >= 0 ? 'up' : 'down'; ?>"><?php echo esc_html(($view_growth >= 0 ? '+' : '') . $view_growth . '%'); ?></em></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Visitors','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($visitors)); ?></strong><em class="<?php echo $visitor_growth >= 0 ? 'up' : 'down'; ?>"><?php echo esc_html(($visitor_growth >= 0 ? '+' : '') . $visitor_growth . '%'); ?></em></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Sessions','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($sessions)); ?></strong><small><?php esc_html_e('unique local sessions','wp-bbuilder'); ?></small></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Pages / session','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($pages_per_session,2)); ?></strong><small><?php esc_html_e('engagement depth','wp-bbuilder'); ?></small></div>
    </div>

    <script type="application/json" id="wpbb-analytics-data"><?php echo wp_json_encode(['daily'=>$daily,'countries'=>$countries,'devices'=>$devices,'referrers'=>$referrers], JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
    <div class="wpbb-analytics-grid wpbb-analytics-grid--2"><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Visits & visitors','wp-bbuilder'); ?></h2><span><?php echo esc_html($days . 'd'); ?></span></div><div id="wpbb-chart-traffic" class="wpbb-chart"></div></div><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Countries','wp-bbuilder'); ?></h2><span><?php esc_html_e('CDN/proxy header','wp-bbuilder'); ?></span></div><div id="wpbb-chart-countries" class="wpbb-chart"></div></div></div>
    <div class="wpbb-analytics-grid wpbb-analytics-grid--2"><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Devices','wp-bbuilder'); ?></h2></div><div id="wpbb-chart-devices" class="wpbb-chart wpbb-chart--small"></div></div><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Acquisition sources','wp-bbuilder'); ?></h2></div><div id="wpbb-chart-referrers" class="wpbb-chart wpbb-chart--small"></div></div></div>

    <div class="wpbb-analytics-grid wpbb-analytics-grid--2">
        <div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Most visited pages','wp-bbuilder'); ?></h2></div><div class="wpbb-table-scroll"><table class="widefat striped"><thead><tr><th><?php esc_html_e('Page','wp-bbuilder'); ?></th><th><?php esc_html_e('Type','wp-bbuilder'); ?></th><th><?php esc_html_e('Views','wp-bbuilder'); ?></th><th><?php esc_html_e('Visitors','wp-bbuilder'); ?></th></tr></thead><tbody><?php if (!$top_pages): ?><tr><td colspan="4"><?php esc_html_e('No visits yet. Generate demo data from Analytics settings or browse the site with tracking enabled.','wp-bbuilder'); ?></td></tr><?php endif; ?><?php foreach ($top_pages as $row): ?><tr><td><strong><?php echo esc_html($row['title'] ?: $row['path']); ?></strong><small><?php echo esc_html($row['path']); ?></small></td><td><?php echo esc_html($row['object_type'] ?: 'page'); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['views'])); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['visitors'])); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
        <div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Most viewed products','wp-bbuilder'); ?></h2></div><div class="wpbb-table-scroll"><table class="widefat striped"><thead><tr><th><?php esc_html_e('Product','wp-bbuilder'); ?></th><th><?php esc_html_e('Views','wp-bbuilder'); ?></th><th><?php esc_html_e('Visitors','wp-bbuilder'); ?></th></tr></thead><tbody><?php if (!$top_products): ?><tr><td colspan="3"><?php esc_html_e('Product views will appear here automatically.','wp-bbuilder'); ?></td></tr><?php endif; ?><?php foreach ($top_products as $row): ?><tr><td><strong><?php echo esc_html($row['title'] ?: $row['path']); ?></strong><small><?php echo esc_html($row['path']); ?></small></td><td><?php echo esc_html(number_format_i18n((int)$row['views'])); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['visitors'])); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </div>
    <p class="wpbb-analytics-footnote"><?php echo esc_html(sprintf(__('Updated %s. WP BBuilder local analytics stores hashed browser/session identifiers and does not store raw visitor IP addresses.','wp-bbuilder'), $generated)); ?></p>
</div>
