<?php if (!defined('ABSPATH')) exit; ?>
<div class="wrap wpbb-analytics-wrap">
    <div class="wpbb-analytics-head">
        <div><span class="wpbb-analytics-kicker">WP BB PLATFORM</span><h1><?php esc_html_e('Website statistics', 'wp-bbuilder'); ?></h1><p><?php esc_html_e('First-party traffic intelligence for pages, products, countries, devices and acquisition sources.', 'wp-bbuilder'); ?></p></div>
        <div class="wpbb-analytics-actions"><a class="button" href="<?php echo esc_url($settings_url); ?>"><?php esc_html_e('Analytics settings', 'wp-bbuilder'); ?></a><a class="button" href="<?php echo esc_url($full_settings_url); ?>"><?php esc_html_e('BBuilder settings', 'wp-bbuilder'); ?></a></div>
    </div>
    <?php if ($error): ?><div class="notice notice-error"><p><?php echo esc_html($error); ?></p></div><?php endif; ?>
    <form class="wpbb-range" method="get"><input type="hidden" name="page" value="wpbb-analytics"><label for="wpbb-range"><?php esc_html_e('Range', 'wp-bbuilder'); ?></label><select id="wpbb-range" name="range"><?php foreach ([7,30,90,180,365] as $d): ?><option value="<?php echo esc_attr($d); ?>" <?php selected($days,$d); ?>><?php echo esc_html(sprintf(_n('%d day','%d days',$d,'wp-bbuilder'),$d)); ?></option><?php endforeach; ?></select><label>From <input type="date" name="start" value="<?php echo esc_attr($window['start']); ?>"></label><label>To <input type="date" name="end" value="<?php echo esc_attr($window['end']); ?>" max="<?php echo esc_attr(current_datetime()->modify('-1 day')->format('Y-m-d')); ?>"></label><label>Dataset <select name="dataset"><option value="real" <?php selected($dataset,'real'); ?>>Real visits only</option><option value="demo" <?php selected($dataset,'demo'); ?>>Demo only</option></select></label><button class="button button-primary">Apply dates</button><button class="button" name="preset" value="1" onclick="this.form.elements.start.value='';this.form.elements.end.value='';">Apply preset</button></form>
    <p class="wpbb-period-note"><strong><?php echo esc_html($dataset==='demo' ? 'DEMO DATA - not real traffic' : 'REAL LOCAL TRAFFIC'); ?></strong> &middot; <?php echo esc_html($window['start'].' to '.$window['end'].' | '.$window['timezone']); ?><br>Comparison: <?php echo esc_html($window['previous_start'].' to '.$window['previous_end']); ?>. Complete days; today is excluded. <?php echo esc_html(number_format_i18n($demo_rows)); ?> synthetic rows are kept separately.</p>
    <?php if (wpbb_get_option('local_analytics_respect_consent',1) && !wpbb_get_option('cookie_consent_enabled',0) && !function_exists('wp_has_consent')): ?><div class="notice notice-warning inline"><p>Tracking is waiting for a consent manager. Enable BBuilder's cookie banner or a WordPress Consent API-compatible manager. No browser identifiers are created while consent is missing.</p></div><?php endif; ?>

    <div class="wpbb-kpis">
        <div class="wpbb-kpi"><span><?php esc_html_e('Page views','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($views)); ?></strong><em class="<?php echo $view_growth >= 0 ? 'up' : 'down'; ?>"><?php echo esc_html(WPBB_Analytics_Window::growth_label($view_growth)); ?></em></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Visitors','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($visitors)); ?></strong><em class="<?php echo $visitor_growth >= 0 ? 'up' : 'down'; ?>"><?php echo esc_html(WPBB_Analytics_Window::growth_label($visitor_growth)); ?></em></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Sessions','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($sessions)); ?></strong><small><?php esc_html_e('unique local sessions','wp-bbuilder'); ?></small></div>
        <div class="wpbb-kpi"><span><?php esc_html_e('Pages / session','wp-bbuilder'); ?></span><strong><?php echo esc_html(number_format_i18n($pages_per_session,2)); ?></strong><small><?php esc_html_e('engagement depth','wp-bbuilder'); ?></small></div>
    </div>

    <script type="application/json" id="wpbb-analytics-data"><?php echo wp_json_encode(['daily'=>$daily,'countries'=>$countries,'devices'=>$devices,'referrers'=>$referrers], JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?></script>
    <div class="wpbb-analytics-grid wpbb-analytics-grid--2"><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Visits & visitors','wp-bbuilder'); ?></h2><span><?php echo esc_html($days . 'd'); ?></span></div><div id="wpbb-chart-traffic" class="wpbb-chart"></div></div><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Countries','wp-bbuilder'); ?></h2><span><?php esc_html_e('Trusted proxy, when configured','wp-bbuilder'); ?></span></div><div id="wpbb-chart-countries" class="wpbb-chart"></div></div></div>
    <div class="wpbb-analytics-grid wpbb-analytics-grid--2"><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Devices','wp-bbuilder'); ?></h2></div><div id="wpbb-chart-devices" class="wpbb-chart wpbb-chart--small"></div></div><div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Acquisition sources','wp-bbuilder'); ?></h2></div><div id="wpbb-chart-referrers" class="wpbb-chart wpbb-chart--small"></div></div></div>

    <div class="wpbb-analytics-grid wpbb-analytics-grid--2">
        <div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Most visited pages','wp-bbuilder'); ?></h2></div><div class="wpbb-table-scroll"><table class="widefat striped"><thead><tr><th><?php esc_html_e('Page','wp-bbuilder'); ?></th><th><?php esc_html_e('Type','wp-bbuilder'); ?></th><th><?php esc_html_e('Views','wp-bbuilder'); ?></th><th><?php esc_html_e('Visitors','wp-bbuilder'); ?></th></tr></thead><tbody><?php if (!$top_pages): ?><tr><td colspan="4"><?php esc_html_e('No visits in this dataset and period. Test real traffic after consent, or choose the separate demo dataset to preview.','wp-bbuilder'); ?></td></tr><?php endif; ?><?php foreach ($top_pages as $row): ?><tr><td><strong><?php echo esc_html($row['title'] ?: $row['path']); ?></strong><small><?php echo esc_html($row['path']); ?></small></td><td><?php echo esc_html($row['object_type'] ?: 'page'); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['views'])); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['visitors'])); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
        <div class="wpbb-analytics-panel"><div class="wpbb-panel-title"><h2><?php esc_html_e('Most viewed products','wp-bbuilder'); ?></h2></div><div class="wpbb-table-scroll"><table class="widefat striped"><thead><tr><th><?php esc_html_e('Product','wp-bbuilder'); ?></th><th><?php esc_html_e('Views','wp-bbuilder'); ?></th><th><?php esc_html_e('Visitors','wp-bbuilder'); ?></th></tr></thead><tbody><?php if (!$top_products): ?><tr><td colspan="3"><?php esc_html_e('Product views will appear here automatically.','wp-bbuilder'); ?></td></tr><?php endif; ?><?php foreach ($top_products as $row): ?><tr><td><strong><?php echo esc_html($row['title'] ?: $row['path']); ?></strong><small><?php echo esc_html($row['path']); ?></small></td><td><?php echo esc_html(number_format_i18n((int)$row['views'])); ?></td><td><?php echo esc_html(number_format_i18n((int)$row['visitors'])); ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </div>
    <?php if ($dataset==='real') WPBB_Analytics_Insights::commerce_html($window); ?>
    <?php WPBB_Google_Analytics::instance()->panel($window, false); ?>
    <p class="wpbb-analytics-footnote"><?php echo esc_html(sprintf(__('Updated %s. WP BBuilder local analytics stores hashed browser/session identifiers and does not store raw visitor IP addresses.','wp-bbuilder'), $generated)); ?></p>
</div>
